### ISSUE TITLE
'ChannelFileWrite' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by mhils** [pytest-dev/pytest-faulthandler#19]
Hi,

I'm running into issues when having both pytest-faulthandler and python-xdist installed:

```
(venv) C:\Users\user\git\mitmproxy>py.test -f
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\main.py", line 92, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\config.py", line 859, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 750, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\user\git\mitmproxy\venv\lib\site-packages\pytest_faulthandler.py", line 23, in pytest_configure
INTERNALERROR>     stderr_fd_copy = os.dup(sys.stderr.fileno())
INTERNALERROR> AttributeError: 'ChannelFileWrite' object has no attribute 'fileno'
############################# waiting for changes #############################
### Watching:   C:\Users\user\git\mitmproxy


(venv) C:\Users\user\git\mitmproxy>pip uninstall pytest-faulthandler
[...]

(venv) C:\Users\user\git\mitmproxy>py.test -f
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: C:\Users\user\git\mitmproxy, inifile: setup.cfg
plugins: xdist-1.15.0, timeout-1.0.0, cov-2.4.0
```

Any hints on how this can be fixed? :smiley:

**Comment by nicoddemus** [comment]
Fixed by #20
