### ISSUE TITLE
Seems to break with pytest 3.2

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-faulthandler#22]
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/main.py", line 106, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/config.py", line 923, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 750, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/Work/miniconda/envs/_ben10-linux64-py27/lib/python2.7/site-packages/pytest_faulthandler.py", line 24, in pytest_configure
INTERNALERROR>     stderr_fd_copy = os.dup(sys.stderr.fileno())
INTERNALERROR> UnsupportedOperation: fileno
```

**Comment by The-Compiler** [comment]
I haven't seen this so far - maybe it's a Python 2 only thing?

**Comment by nicoddemus** [comment]
Hmm might be, indeed the traceback is from Python 2.7.

**Comment by nicoddemus** [comment]
I'm closing this as I'm no longer able to reproduce it. Might have been a hiccup on our CI system.
