### ISSUE TITLE
--faulthandler-timeout on Windows/Py27 CI runs blows up

### ISSUE THREAD

**Issue by j9ac9k** [pytest-dev/pytest-faulthandler#32]
Issue seems to be identical to #8, was thinking . about commenting there but given that was 4 years ago, I thought I would open my own issue.

On azure-pipelines I . call pytest in the following fashion

```
      python -m pytest -sv \
        --junitxml=junit/test-results.xml \
        --cov pyqtgraph --cov-report=xml --cov-report=html \
        --faulthandler-timeout=60
```

When I make this call on my Windows/Python2.7 runs I get the following error:

```
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/a5488e34-446c-41fb-9365-433e149de497.sh
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\_pytest\main.py", line 201, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\_pytest\config\__init__.py", line 668, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Miniconda\envs\test-environment-2.7\lib\site-packages\pytest_faulthandler.py", line 40, in pytest_configure
INTERNALERROR>     config.warn(code='C1', message=message)
INTERNALERROR> AttributeError: 'Config' object has no attribute 'warn'
##[error]Bash exited with code '3'.
```

For all the other python/OS configurations besides PyQt4/PySide1 - Windows - Python2.7 it runs just fine.

**Comment by nicoddemus** [comment]
Hi @j9ac9k,

Thanks for reporting this.

The problem is that this python/OS configuration is reaching this warning:

https://github.com/pytest-dev/pytest-faulthandler/blob/326c21011bd92397cd86b6446b324f01f1e793ba/pytest_faulthandler.py#L38-L40

`config.warn` no longer exists since pytest 4.0. I will work on a fix. 👍

**Comment by j9ac9k** [comment]
@nicoddemus thanks for the fast response!  Please let me know if there is anything I can do to assist/help.

**Comment by nicoddemus** [comment]
`1.6.0` released with this fix! Thanks again for the report.

**Comment by j9ac9k** [comment]
Thanks for the insanely fast fix/release!
